meetingApp/Controllers/MeetingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using meetingApp.Models;
using System.Security.Claims;

namespace meetingApp.Controllers
{
    public class MeetingController : Controller
    {
        private static List<int> idUserBefore = new List<int>() { 0, 0, 0, 0, 0};

        [Authorize]
        public IActionResult MeetingPage()
        {

            return View();
        }

        public JsonResult GetJsonUser()
        {
            using (MeetingAppContext db = new MeetingAppContext())
            {
                var usersID = from user in db.Users.ToList()
                            orderby user.IdUser
                            select user.IdUser;
                int randomUserId = rndId(usersID);
                while (randomUserId == Convert.ToInt32(User.FindFirst(ClaimTypes.Name).Value) || idUserBefore.Contains(randomUserId))
                {
                    randomUserId = rndId(usersID);
                }
                User? rndUser = db.Users.FirstOrDefault(u => u.IdUser == randomUserId);
                idUserBefore.RemoveAt(0);
                idUserBefore.Add(randomUserId);
                return Json(rndUser);
            }
        }

        public JsonResult GetAdress(int id)
        {
            using (MeetingAppContext db = new MeetingAppContext())
            {
                Adress? adr = db.Adresses.FirstOrDefault(u => u.IdUser == id);
                City? c = db.Cities.FirstOrDefault(c => c.IdCity == adr.IdCity);
                return Json(c);
            }
        }

        public JsonResult GetDescr(int id)
        {
            using (MeetingAppContext db = new MeetingAppContext())
            {
                Description? des = db.Descriptions.FirstOrDefault(d => d.IdUser == id);
                if(des != null)
                {
                    return Json(des);
                }
                return Json(null);
            }
        }

        public JsonResult GetImg(int id)
        {
            using (MeetingAppContext db = new MeetingAppContext())
            {
                Photo? img = db.Photos.FirstOrDefault(p => p.IdUser == id);
                if(img != null) return Json(img);
                return Json(null);
            }
        }

        public IActionResult DoMatch(int UserId)
        {
            using(MeetingAppContext db = new MeetingAppContext())
            {
                Match? match = new Match();
                match.IdUser1 = Convert.ToInt32(User.FindFirst(ClaimTypes.Name).Value);
                match.IdUser2 = UserId;
                db.Matches.Add(match);
                db.SaveChanges();
                return RedirectToAction("UserPage", "User", new {id = match.IdUser1});
            }
        }

        [Authorize]
        public IActionResult Like(int? idMatch)
        {
            using(MeetingAppContext db = new MeetingAppContext())
            {
                if (idMatch != null)
                {
                    Match? match = db.Matches.FirstOrDefault(m => m.IdMatch == idMatch);
                    if (match != null)
                    {
                        match.StatId = 1;
                        db.Matches.Update(match);
                        db.SaveChanges();
                        return RedirectToAction("UserPage", "User", new { id = User.FindFirst(ClaimTypes.Name).Value });
                    }
                    else
                    {
                        return RedirectToAction("UserPage", "User", new { id = User.FindFirst(ClaimTypes.Name).Value });
                    }
                }
                else
                {
                    return NotFound();
                }
            }
        }


        [NonAction]
        private int rndId(IEnumerable<int> usersId)
        {
            Random random = new Random();
            int index = random.Next(0, usersId.Count());
            return usersId.ElementAt(index);

        }
    }
}

meetingApp/Views/Meeting/MeetingPage.cshtml
@section Scripts {
	<script src="~/scripts/getRndUser.js"></script>
}
@section Styles{
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/start.css">
}
@{
	ViewBag.StartMeet = "";
	ViewBag.Profile = "Профиль";
	ViewBag.Exit = "Выйти";
	ViewData["Title"] = "Начать знакомиться";


}

<button class="findBtn">Найти</button>

<form asp-action="DoMatch" asp-controller="Meeting" id="meetingForm">
	<input type="hidden" name="UserId" id="UserId"/>
    <div class="containerr">
        <div class="user_Card">
            <div class="userImage">
                <div class="oo">
                    <img id="image" src="~/img/avatar.jpg" />
                </div>
            </div>
           
	            <div class="infoUser">
                    <div class="FIO">
		                <div id="userName" class="fam"></div>
                    </div>

                 <div class="info">
		          <div class="pol">
                        <p class="ttt">Пол: </p>
                        <p class="sex" id="Sex"> </p>
                  </div>

                   <div class="birth">
                       <p class="ttt">День рождения: </p>
                       <p class="birth" id="birth"> </p>
                   </div>

                    <div class="city">
                        <p class="ttt">Город: </p>
                        <p class="birth" id="city"> </p>
                    </div>
                </div>


                 <div class="about">
                    <div id="descr">
                        <p id="des"></p>
                    </div>
                </div>
                   
	            </div>
           
        </div>
    </div>
</form>
@*

<form asp-action="DoMatch" asp-controller="Meeting" id="meetingForm">
    <input type="hidden" name="UserId" id="UserId" />
    <div class="container">
        <div class="user_Card">
            <div class="userImage">
                <div class="oo">
                    <img src="~/img/Арина.jpg">
                </div>
            </div>

            <div class="infoUser">
                <div class="FIO">
                    <div class="fam" id="fam"></div>
                    <div class="name" id="name"></div>
                </div>
                <div class="info">
                    <div class="sex" id="sex"><b class="ttt">Пол: </b></div>
                    <div class="birth" id="birth"><b class="ttt">День рождения: </b></div>
                    <div class="city" id="city"><b class="ttt">Город: </b> </div>
                </div>
                <div class="about">
                    <div id="descr"><p></p></div>
                    <div class="buttons">
                        <button class="findBtn" style="display:none" id="RejectBtn">Отклонить</button>
                        <button class="like" style="display:none" id="LikeBtn">Лайк</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>*@
<div class="buttons">
    <button style="display:none" id="RejectBtn" class="findBtn fu">Отклонить</button>
    <button style="display:none" id="LikeBtn" class="like">Лайк</button>
</div>